- name: remove app dir
  file:
    state: absent
    path: /srv/talkboy-9000/
- name: create app dir
  file:
    path: /srv/talkboy-9000
    state: directory
- name: extract app
  unarchive:
    src: ../../../../app.zip
    dest: /srv/talkboy-9000
