---

- name: reboot host=({{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}) port=({{ ansible_port }})
  become: true
  shell: nohup bash -c 'sleep 2 && shutdown -r now "ansible reboot-host"' &
  async: 0
  poll: 0
  ignore_errors: true

- name: wait for host=({{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}) port=({{ ansible_port }})
  become: false
  local_action: wait_for host='{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}' port='{{ ansible_port }}' search_regex='OpenSSH' state='started' delay=15 timeout=300
